import horsting as h
import time 

uris = [
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
  "http://fps.io/plugins/state-variable-filter-v2",
]

units = [h.lv2(uri) for uri in uris]

h.connect(h.system, *units, h.system)
